@startwbs
+ GitHubExplorer
 + app
  + activity
  + compose
  + mapper
  + model
  + theme
  + viewmodel
 + domain
  + di
  + model
  + usecases
  + repo def
 + data
  + di
  + repositories Impl
   + datasources
   + local
    + entities
    + mapper
    + db
    + sharedpreferences
   + remote
    + api
    + mapper
    + dto
@endwbs